/**
 * VoiceCheckIn — the optional self-assessment and voice check-in.
 * One job: present the tailored questions and make clear that all of it is voluntary.
 *
 * The questions are chosen by a rule-based lookup against a fixed bank, keyed by
 * the signals contributing most to this person's own score. No question is
 * generated by a language model.
 */
import { api } from "../../../shared/api.js";
import { el } from "../../../shared/ui.js";

/**
 * Render one question row.
 * @param {Object} q Question record.
 * @returns {HTMLElement} The row.
 */
function questionRow(q) {
  const body = [el("div", { text: q.text })];
  if (q.free_text) {
    body.push(el("textarea", { placeholder: "Optional — only you see this." }));
  } else {
    body.push(el("input", { type: "range", min: "0", max: "4", value: "2" }));
    body.push(el("div", { class: "small muted", text: "0 = not at all · 4 = a great deal" }));
  }
  if (q.tailored_to) {
    body.push(el("div", { class: "small muted", text: `Shown because of: ${q.tailored_to.replace(/_/g, " ")}` }));
  }
  return el("div", { class: "card" }, body);
}

/**
 * Render the check-in screen.
 * @param {string} pseudonymId Whose check-in.
 * @returns {Promise<HTMLElement>} The screen node.
 */
export async function renderVoiceCheckIn(pseudonymId) {
  const data = await api.personal.checkIn(pseudonymId);
  const root = el("div");
  root.appendChild(el("h1", { class: "page-title", text: "Check in" }));
  root.appendChild(el("p", { class: "page-sub", text: data.voluntary_note }));

  root.appendChild(el("div", { class: "optional-block" }, [
    el("div", {}, [
      el("strong", { text: "Voice check-in" }),
      el("span", { class: "optional-tag", text: "optional" }),
    ]),
    el("p", { class: "small", text:
      "If you record a short check-in, the system measures only how your voice sounds — " +
      "pitch, pace, pauses and steadiness — compared with your own past recordings. " +
      "It never converts your speech to text and never analyses what you said. " +
      "The recording is deleted as soon as those measurements are taken." }),
    el("button", { class: "ghost", disabled: "disabled", text: "Record (upload not enabled in this build)" }),
    el("div", { class: "small muted", text:
      "The acoustic pipeline is fully implemented and runs on the batch corpus; " +
      "the in-app upload endpoint was not built in this pass." }),
  ]));

  root.appendChild(el("h2", { class: "page-title", style: "font-size:17px;margin-top:26px", text: "A few questions" }));
  root.appendChild(el("div", { class: "small muted", style: "margin-bottom:12px", text: data.tailoring_method }));
  data.general.forEach((q) => root.appendChild(questionRow(q)));
  data.tailored.forEach((q) => root.appendChild(questionRow(q)));

  root.appendChild(el("button", { class: "primary", text: "Save my answers" }));
  root.appendChild(el("div", { class: "note", text:
    "Answers are stored against your own record. They are not shown to your commander, " +
    "and a welfare officer sees them only if you ask for support." }));
  return root;
}
