"""Version every trained model, so any historical score can be traced.

One job: write a fitted model plus its metadata to disk under a version id, and
load it back.

Why versioning is not optional here
-----------------------------------
A welfare-risk score can lead to a welfare officer contacting a named person.
If someone later asks "why was this person flagged in September?", the answer
has to name the model that produced the score, the data it was trained on, the
thresholds in force, and the feature order it expected. Without a registry that
question is unanswerable, and "the system said so" is not an acceptable answer
in a system that must be defensible.

Each version directory contains:
    ``model.joblib``    the fitted estimator
    ``metadata.json``   feature order, metrics, thresholds, provenance

The feature order is stored because it is the single most dangerous thing to
get wrong silently: a model handed its inputs in a different order will return
confident, wrong numbers with no error. :func:`load` checks it on every load.
"""

from __future__ import annotations

import json
import platform
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional, Sequence

import joblib
import sklearn

from backend.config import settings

MODEL_FILENAME = "model.joblib"
METADATA_FILENAME = "metadata.json"
CURRENT_POINTER_FILENAME = "CURRENT"


@dataclass
class ModelMetadata:
    """Everything needed to reproduce and audit one trained model.

    Attributes:
        version: Version identifier, ``v<UTC timestamp>``.
        model_name: Candidate name, e.g. ``random_forest``.
        display_name: Human-readable algorithm name.
        is_tree_based: Whether an exact tree SHAP explainer applies.
        feature_names: Exact input order the model expects.
        target_name: Name of the predicted quantity.
        metrics: Held-out metrics as measured at selection time. Never
            recomputed on the refitted model.
        selection_reason: Why this candidate was chosen over the others.
        training_rows: Rows used in the final refit.
        training_people: Distinct people in that refit.
        risk_thresholds: The band cutoffs in force when this model was trained.
        created_at: UTC ISO timestamp.
        library_versions: Versions of the libraries that produced the artefact.
        data_provenance: Where the training data came from.
        label_provenance: What the metrics were measured *against*. Required:
            :func:`save` refuses to write a version without it. Metrics and
            the statement of what they mean travel in the same file so that a
            number cannot be quoted without its provenance being one field
            away. Defaults to ``settings.LABEL_PROVENANCE`` at the call site,
            never here -- an empty default would make it optional in practice.
        conformal: Calibration block written by ``backend/models/conformal``
            -- method, coverage, half-width, and what it was calibrated on.
            None for a model registered without calibration.
        deployed_metrics: Held-out metrics of the *deployed* artefact itself,
            measured on the test people it never saw. ``metrics`` above are
            the selection-time numbers for the candidate as fitted on all
            training people; the two differ because the deployed model gives
            up a calibration slice.
    """

    version: str
    model_name: str
    display_name: str
    is_tree_based: bool
    feature_names: List[str]
    target_name: str
    metrics: Dict[str, float]
    selection_reason: str
    training_rows: int
    training_people: int
    risk_thresholds: Dict[str, float]
    created_at: str
    library_versions: Dict[str, str] = field(default_factory=dict)
    data_provenance: str = ""
    label_provenance: str = ""
    conformal: Optional[Dict[str, object]] = None
    deployed_metrics: Optional[Dict[str, float]] = None

    def to_dict(self) -> Dict[str, object]:
        """Return a JSON-serialisable form."""
        return asdict(self)


def _new_version_id() -> str:
    """Return a fresh, sortable version identifier."""
    return "v" + datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def save(
    estimator,
    model_name: str,
    display_name: str,
    is_tree_based: bool,
    metrics: Dict[str, float],
    selection_reason: str,
    training_rows: int,
    training_people: int,
    feature_names: Sequence[str] = settings.MODEL_FEATURE_NAMES,
    registry_dir: Path | None = None,
    data_provenance: str = "synthetic corpus generated by scripts/generate_synthetic_data.py",
    label_provenance: str = "",
    mark_current: bool = True,
    conformal: Optional[Dict[str, object]] = None,
    deployed_metrics: Optional[Dict[str, float]] = None,
) -> Path:
    """Persist a fitted model and its metadata under a new version.

    Args:
        estimator: The fitted estimator to store.
        model_name: Candidate name.
        display_name: Human-readable algorithm name.
        is_tree_based: Whether an exact tree SHAP explainer applies.
        metrics: Held-out metrics measured at selection time.
        selection_reason: Why this model was chosen.
        training_rows: Rows in the final refit.
        training_people: Distinct people in the final refit.
        feature_names: Input order the model expects.
        registry_dir: Registry root. Defaults to the configured directory.
        data_provenance: Free-text description of the training data source.
        label_provenance: What ``metrics`` were measured against. **Required**
            -- pass ``settings.LABEL_PROVENANCE``. Empty raises, because a
            registry entry whose metrics carry no statement of what they mean
            is the exact artefact this project keeps re-creating by accident.
        mark_current: Whether to point ``CURRENT`` at this version.
        conformal: Calibration block from ``conformal.calibrate().to_dict()``,
            plus any verification figures the trainer adds.
        deployed_metrics: The deployed artefact's own held-out metrics.

    Returns:
        Path of the created version directory.

    Raises:
        ValueError: If ``label_provenance`` is empty.

    Note:
        Previous versions are never overwritten or deleted. A score produced in
        the past stays explicable even after the model is replaced.
    """
    if not label_provenance.strip():
        raise ValueError(
            "label_provenance is required: a registry entry must record what "
            "its metrics were measured against. Pass settings.LABEL_PROVENANCE."
        )
    registry_dir = Path(registry_dir or settings.MODEL_REGISTRY_DIR)
    version = _new_version_id()
    version_dir = registry_dir / version
    version_dir.mkdir(parents=True, exist_ok=True)

    joblib.dump(estimator, version_dir / MODEL_FILENAME)

    metadata = ModelMetadata(
        version=version,
        model_name=model_name,
        display_name=display_name,
        is_tree_based=is_tree_based,
        feature_names=list(feature_names),
        target_name=settings.MODEL_TARGET_NAME,
        metrics=dict(metrics),
        selection_reason=selection_reason,
        training_rows=training_rows,
        training_people=training_people,
        risk_thresholds={
            "moderate_min": settings.RISK_BAND_MODERATE_MIN,
            "high_min": settings.RISK_BAND_HIGH_MIN,
        },
        created_at=datetime.now(timezone.utc).isoformat(),
        library_versions={
            "python": platform.python_version(),
            "scikit-learn": sklearn.__version__,
            "joblib": joblib.__version__,
        },
        data_provenance=data_provenance,
        label_provenance=label_provenance,
        conformal=dict(conformal) if conformal else None,
        deployed_metrics=dict(deployed_metrics) if deployed_metrics else None,
    )
    (version_dir / METADATA_FILENAME).write_text(
        json.dumps(metadata.to_dict(), indent=2), encoding="utf-8"
    )

    if mark_current:
        (registry_dir / CURRENT_POINTER_FILENAME).write_text(version, encoding="utf-8")
    return version_dir


def list_versions(registry_dir: Path | None = None) -> List[str]:
    """List stored versions, newest last.

    Args:
        registry_dir: Registry root.

    Returns:
        Sorted version identifiers. The id format is sortable by construction.
    """
    registry_dir = Path(registry_dir or settings.MODEL_REGISTRY_DIR)
    if not registry_dir.exists():
        return []
    return sorted(
        d.name for d in registry_dir.iterdir() if d.is_dir() and (d / METADATA_FILENAME).exists()
    )


def current_version(registry_dir: Path | None = None) -> str | None:
    """Return the version the ``CURRENT`` pointer names.

    Args:
        registry_dir: Registry root.

    Returns:
        The version id, or None when nothing has been registered. Falls back to
        the newest stored version if the pointer file is missing.
    """
    registry_dir = Path(registry_dir or settings.MODEL_REGISTRY_DIR)
    pointer = registry_dir / CURRENT_POINTER_FILENAME
    if pointer.exists():
        version = pointer.read_text(encoding="utf-8").strip()
        if (registry_dir / version / METADATA_FILENAME).exists():
            return version
    versions = list_versions(registry_dir)
    return versions[-1] if versions else None


def load(version: str | None = None, registry_dir: Path | None = None):
    """Load a stored model and its metadata.

    Args:
        version: Version to load. Defaults to the ``CURRENT`` pointer.
        registry_dir: Registry root.

    Returns:
        Tuple of (fitted estimator, :class:`ModelMetadata`).

    Raises:
        FileNotFoundError: If no model has been registered, or the requested
            version does not exist.
        ValueError: If the stored feature order does not match the feature
            order the code currently expects. This is checked on every load
            because a mismatch produces confident, wrong predictions rather
            than an error -- the worst possible failure mode for this system.
    """
    registry_dir = Path(registry_dir or settings.MODEL_REGISTRY_DIR)
    version = version or current_version(registry_dir)
    if version is None:
        raise FileNotFoundError(
            f"no model registered in {registry_dir} -- run scripts/train_models.py first"
        )
    version_dir = registry_dir / version
    if not (version_dir / MODEL_FILENAME).exists():
        raise FileNotFoundError(f"model version '{version}' not found in {registry_dir}")

    estimator = joblib.load(version_dir / MODEL_FILENAME)
    metadata = ModelMetadata(
        **json.loads((version_dir / METADATA_FILENAME).read_text(encoding="utf-8"))
    )

    expected = list(settings.MODEL_FEATURE_NAMES)
    if metadata.feature_names != expected:
        raise ValueError(
            f"model version '{version}' expects features {metadata.feature_names} "
            f"but the code now supplies {expected}. Retrain before serving; a model "
            f"given its inputs in a different order returns confident wrong numbers."
        )
    return estimator, metadata
